# AUTOGENERATED! DO NOT EDIT! File to edit: 05_datacollect.ipynb (unless otherwise specified).

__all__ = ['main']

# Cell
from sandbox.rocky.tf.algos.trpo import TRPO
from sandbox.rocky.tf.envs.base import TfEnv
from sandbox.rocky.tf.policies.gaussian_mlp_policy import GaussianMLPPolicy
from rllab.baselines.linear_feature_baseline import LinearFeatureBaseline
from rllab.envs.gym_env import GymEnv

from airl.utils.log_utils import rllab_logdir

def main():
    #env = TfEnv(GymEnv('BipedalWalker-v2', record_video=False, record_log=False))
    #env = TfEnv(GymEnv('CarRacing-v0', record_video=False, record_log=False))
    env = TfEnv(GymEnv('MountainCarContinuous-v0', record_video=False, record_log=False))
    policy = GaussianMLPPolicy(name='policy', env_spec=env.spec, hidden_sizes=(32, 32))
    algo = TRPO(
        env=env,
        policy=policy,
        n_itr=200,
        batch_size=2000,
        max_path_length=100,
        discount=0.99,
        store_paths=True,
        baseline=LinearFeatureBaseline(env_spec=env.spec)
        #baseline=GaussianMLPBaseline(env_spec=env.spec)
    )

    #with rllab_logdir(algo=algo, dirname='data/bipedalwalker'):
    with rllab_logdir(algo=algo, dirname='data/mountaincarcontinuous'):
        algo.train()

if __name__ == "__main__":
    main()